const categoryUrls = {
            "vegetables": "https://order-1ib.pages.dev/Vegetables.html",
            "fruits": "https://order-1ib.pages.dev/Fruits.html",
            "oils": "https://order-1ib.pages.dev/Oils.html",
            "beverages": "https://order-1ib.pages.dev/Beverages.html",           
            "delicatessen": "https://order-1ib.pages.dev/Delicatessen.html",
            "eggs": "https://order-1ib.pages.dev/Eggs.html",
            "meat": "https://order-1ib.pages.dev/Meat.html",
            "bakery": "https://order-1ib.pages.dev/Bakery.html",
            "spices": "https://order-1ib.pages.dev/Spices.html",
            "rice & grains": "https://order-1ib.pages.dev/Rice & Grains.html",
            "frozen": "https://order-1ib.pages.dev/Frozen.html",
            "ready to cook": "https://order-1ib.pages.dev/Ready to cook.html",
            "snacks": "https://order-1ib.pages.dev/Snacks.html",
            "beauty": "https://order-1ib.pages.dev/Beauty.html",
            "babies": "https://order-1ib.pages.dev/Babies.html",
            "personal": "https://order-1ib.pages.dev/Personal.html",
            "nuts": "https://order-1ib.pages.dev/Nuts.html",
            "tea": "https://order-1ib.pages.dev/Tea.html",
            "home": "https://order-1ib.pages.dev/Home.html",
            "seafood": "https://order-1ib.pages.dev/Seafood.html",
            "cafeteria": "https://order-1ib.pages.dev/Cafeteria.html",
            "restaurant": "https://order-1ib.pages.dev/Restaurant.html",
            "fastfood": "https://order-1ib.pages.dev/Fastfood.html",
            "stores": "https://order-1ib.pages.dev/Stores.html"
        };
