const categoryUrls = {
            "vegetables": "https://order-1ib.pages.dev/Vegetables.html",
            "fruits": "https://order-1ib.pages.dev/Fruits.html",
            "oils": "https://order-1ib.pages.dev/Oils.html",
            "beverages": "https://order-1ib.pages.dev/Beverages.html",           
            "delicatessen": "https://order-1ib.pages.dev/Delicatessen.html",
            "eggs": "https://order-1ib.pages.dev/Eggs.html",
            "meat": "https://order-1ib.pages.dev/Meat.html",
            "bakery": "https://order-1ib.pages.dev/Bakery.html",
            "spices": "https://order-1ib.pages.dev/Spices.html",
            "rice & grains": "https://order-1ib.pages.dev/Rice & Grains.html",
            "frozen": "https://order-1ib.pages.dev/Frozen.html",
            "ready to cook": "https://order-1ib.pages.dev/Ready to cook.html",
            "snacks": "https://order-1ib.pages.dev/Snacks.html",
            "nuts": "https://order-1ib.pages.dev/Nuts.html",
            "tea": "https://order-1ib.pages.dev/Tea.html",
            "babies": "https://order-1ib.pages.dev/Babies.html",
            "home": "https://order-1ib.pages.dev/Home.html",
            "beauty": "https://order-1ib.pages.dev/Beauty.html",
            "personal": "https://order-1ib.pages.dev/Personal.html",
            "fitness": "https://nearbys.pages.dev/Fitness",
            "cafeteria": "https://order-1ib.pages.dev/Cafeteria.html",
            "restaurant": "https://order-1ib.pages.dev/Restaurant.html",
            "fastfoods": "https://order-1ib.pages.dev/Fastfood.html",
            "appliences": "https://nearbys.pages.dev/Appliences",
            "accessories": "https://nearbys.pages.dev/Accessories",
            "watches": "https://nearbys.pages.dev/Watches",
            "kids": "https://nearbys.pages.dev/Kids",
            "ladies": "https://nearbys.pages.dev/Ladies",
            "men": "https://nearbys.pages.dev/Men",
            "shoes": "https://nearbys.pages.dev/Shoes",
            "bags": "https://nearbys.pages.dev/Bags",
            "glasses": "https://nearbys.pages.dev/Glasses",
            "samsung": "https://nearbys.pages.dev/Samsung",
            "stores": "https://order-1ib.pages.dev/Stores.html"
        };
