const categoryUrls = {
            "vegetables": "https://order-1ib.pages.dev/Vegetables.html",
            "fruits": "https://order-1ib.pages.dev/Fruits.html",
            "oils": "https://order-1ib.pages.dev/Oils.html",
            "beverages": "https://order-1ib.pages.dev/Beverages.html",           
            "delicatessen": "https://order-1ib.pages.dev/Delicatessen.html",
            "eggs": "https://order-1ib.pages.dev/Eggs.html",
            "meat": "https://order-1ib.pages.dev/Meat.html",
            "bakery": "https://order-1ib.pages.dev/Bakery.html",
            "spices": "https://order-1ib.pages.dev/Spices.html",
            "rice & grains": "https://order-1ib.pages.dev/Rice & Grains.html",
            "frozen": "https://order-1ib.pages.dev/Frozen.html",
            "ready to cook": "https://order-1ib.pages.dev/Ready to cook.html",
            "snacks": "https://order-1ib.pages.dev/Snacks.html",
            "beauty": "https://order-1ib.pages.dev/Beauty.html",
            "meat": "https://order-1ib.pages.dev/Meat.html",
            "meat": "https://order-1ib.pages.dev/Meat.html",
            "meat": "https://order-1ib.pages.dev/Meat.html",
            "seafood": "https://order-1ib.pages.dev/Seafood.html"
        };
